const C=document.getElementById('game'),g=C.getContext('2d'),W=960,H=540;
const levelEl=document.getElementById('level'),livesEl=document.getElementById('lives'),powerEl=document.getElementById('power'),scoreEl=document.getElementById('score'),overlay=document.getElementById('overlay'),title=document.getElementById('overlayTitle'),text=document.getElementById('overlayText'),start=document.getElementById('startBtn'),pause=document.getElementById('pauseBtn'),shell=document.getElementById('gameShell'),toast=document.getElementById('toast'),energy=document.getElementById('energyBar'),badge=document.getElementById('levelBadge'),banner=document.getElementById('gameBanner'),bestEl=document.getElementById('bestScoreHint'),restartBtn=document.getElementById('restartBtn'),jumpBtn=document.getElementById('jumpBtn');
let level=1,lives=3,power=0,score=0,best=+localStorage.getItem('onamOdysseyBest')||0,running=false,paused=false,last=0,t=0,wave=1,raf=0,defending=false,attackTimer=0,inv=0;
let player={lane:1,x:480,y:390,w:38,h:64,vx:0,vy:0,ground:true,jumpT:0};
let goal={x:0,y:0,w:0,h:0},foot={x:650,y:-220,vy:0,tele:0,landed:false,hp:1,visible:false,stun:0};
const keys={left:false,right:false};
let umb=[],hazards=[],particles=[],dodgeMarks=[],distance=0;
const hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const msg=s=>{toast.textContent=s;toast.classList.add('show');clearTimeout(msg.t);msg.t=setTimeout(()=>toast.classList.remove('show'),950)};
const vibrate=n=>{try{navigator.vibrate?.(n)}catch(e){}};
function hud(){levelEl.textContent=level;livesEl.textContent=lives;powerEl.textContent=power;scoreEl.textContent=score;bestEl.textContent='🏆 Best Score: '+best;badge.textContent=level===1?'🌼 LEVEL 1 • MAVELI’S RUN':'☂ LEVEL 2 • VAMANA’S CHALLENGE';banner.textContent=level===1?'HELP MAVELI REACH THE TOP!':'DODGE, DEFEND & ATTACK WITH YOUR UMBRELLA!';document.body.classList.toggle('level-two',level===2);for(let i=0;i<6;i++)energy.children[i].classList.toggle('on',power>=(i+1)*6);if(jumpBtn)jumpBtn.disabled=level!==1}
function burst(x,y,n=16,c='#ffe37a'){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=55+Math.random()*190;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.45+Math.random()*.65,c,size:0})}}
function floatText(x,y,s){particles.push({x,y,vx:0,vy:-42,life:1.05,c:'#fff1a1',size:18,text:s})}
function particlesTick(dt){for(const q of particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=150*dt;q.life-=dt}particles=particles.filter(q=>q.life>0);for(const d of dodgeMarks){d.life-=dt;d.y-=20*dt}dodgeMarks=dodgeMarks.filter(d=>d.life>0)}
function fresh(){cancelAnimationFrame(raf);level=1;lives=3;power=0;score=0;paused=false;defending=false;attackTimer=0;inv=0;keys.left=keys.right=false;setup1();hud()}
function setup1(){umb=[];hazards=[];particles=[];dodgeMarks=[];distance=0;wave=1;t=0;player={lane:1,x:480,y:390,w:38,h:64,vx:0,vy:0,ground:true,jumpT:0};for(let i=0;i<18;i++){const lane=(i*7+2)%3;umb.push({lane,z:650+i*300+(i%3)*70,got:false,bob:i*.7})}goal={x:0,y:0,w:0,h:0}}
function setup2(){hazards=[];particles=[];player={lane:1,x:455,y:H-112,w:34,h:52,vx:0,vy:0,ground:true,jumpT:0};foot={x:650,y:-220,vy:0,tele:0,landed:false,hp:1,visible:false,stun:0};defending=false;attackTimer=0;t=0}
function show(a,b,c){title.textContent=a;text.innerHTML=b;start.textContent=c;overlay.classList.add('show');hud()}
function hide(){overlay.classList.remove('show')}
function jump(){if(level!==1){msg('JUMP IS DISABLED ON GROUND');return}if(player.ground&&!paused&&running){player.vy=-470;player.ground=false;player.jumpT=0;vibrate(20);msg('JUMP!')}}
function changeLane(dir){if(!running||paused)return;const old=player.lane;player.lane=Math.max(0,Math.min(2,player.lane+dir));if(old!==player.lane){vibrate(12);msg(player.lane===0?'LEFT LANE':player.lane===2?'RIGHT LANE':'CENTER LANE')}}
function move(dt){if(level===1){const target=150+player.lane*330;player.x+=(target-player.x)*Math.min(1,dt*13);if(keys.left)changeLane(-1),keys.left=false;if(keys.right)changeLane(1),keys.right=false;player.vy+=1250*dt;player.y+=player.vy*dt;if(player.y>=390){player.y=390;player.vy=0;player.ground=true}else player.ground=false;player.jumpT+=dt}else{const s=260;player.vx=keys.left?-s:keys.right?s:0;player.x=Math.max(30,Math.min(W-player.w-30,player.x+player.vx*dt));player.y=H-112;player.ground=true}inv=Math.max(0,inv-dt);attackTimer=Math.max(0,attackTimer-dt)}
function defend(){if(level!==2||!running||paused)return;if(power<6){msg('NEED 6 ☂ POWER');return}power-=6;defending=true;inv=.15;burst(player.x+17,player.y+22,30,'#9cecff');msg('SHIELD ACTIVATED! 🛡');hud()}
function attack(){if(level!==2||!running||paused)return;if(power<6){msg('NEED 6 ☂ POWER');return}if(!foot.visible||foot.tele>0){msg('WAIT FOR THE FOOT!');return}const d=Math.abs(player.x+17-(foot.x+130));power=0;attackTimer=.65;burst(player.x+40,player.y+18,25,'#ffe47b');if(d<310){foot.hp--;score+=150;foot.stun=1.35;msg('SPEAR HIT! +150');if(foot.hp<=0){foot.visible=false;foot.y=-240;burst(480,250,100,'#ffe47b');best=Math.max(best,score);localStorage.setItem('onamOdysseyBest',best);setTimeout(win,650)}}else msg('SPEAR MISSED — MOVE CLOSER');hud()}
function damage(stomp=false){if(stomp&&defending){defending=false;inv=.55;burst(player.x+17,player.y+22,40,'#9cecff');msg('STOMP BLOCKED! 🛡');hud();return}if(inv>0)return;lives--;inv=1.15;score=Math.max(0,score-10);burst(player.x+17,player.y+22,22,'#ff9c6b');msg(stomp?'STOMP HIT! -1 ❤️':'OBSTACLE HIT! -1 ❤️');if(lives<=0){running=false;show('TRY AGAIN','Maveli ran out of lives.','RETRY')}else{player.lane=1;player.x=level===1?480:455;player.y=level===1?390:H-112;player.vy=0}hud()}
function spawnHazard(){const lane=Math.floor(Math.random()*3);const r=Math.random();const kind=r<.52?'coconut':r<.80?'barricade':'train';hazards.push({lane,z:1050,kind,hit:false,scored:false,rot:0})}
function level1(dt){t+=dt;distance+=dt*(1+wave*.08);wave=distance>38?3:distance>20?2:1;const interval=wave===1?1.35:wave===2?1.02:.78;if(Math.random()<dt/interval)spawnHazard();
for(const u of umb){if(u.got)continue;u.z-=dt*230;u.bob+=dt*5;if(u.z<120&&u.z>-35&&u.lane===player.lane){const jumping=!player.ground;if(!jumping){u.got=true;power=Math.min(36,power+6);score+=25;burst(player.x+19,player.y+20,18);floatText(player.x,player.y-12,'+25  ☂ +6');msg('+6 ☂ POWER');hud()}}if(u.z<-50)u.got=true}
for(const h of hazards){h.z-=dt*(260+wave*55);h.rot+=dt*8;const sx=150+h.lane*330;const approaching=h.z<125&&h.z>-45;if(approaching&&h.lane===player.lane&&!h.hit){const jumping=!player.ground&&player.y<350;if(jumping){h.hit=true;score+=5;floatText(player.x,player.y-15,'+5 Points');burst(player.x,player.y+20,12,'#ffe37a');msg(h.kind==='coconut'?'+5 COCONUT DODGE':h.kind==='train'?'+5 TRAIN DODGE':'+5 PERFECT JUMP');hud()}else{h.hit=true;damage(false)}}if(!h.scored&&h.z<70){h.scored=true;if(h.lane!==player.lane){score+=5;dodgeMarks.push({x:sx-35,y:310,life:1});floatText(sx-35,285,'+5 Points');msg('+5 CLOSE DODGE');hud()}}}hazards=hazards.filter(h=>h.z>-120);
if(distance>50){score+=200;setup2();level=2;running=false;hud();show('LEVEL 2 • VAMANA’S CHALLENGE','Maveli escaped the festive lanes! Your umbrella power carries forward.<br><br><b>DEFEND:</b> 6 ☂ blocks the next stomp. <b>ATTACK:</b> uses all power.','ENTER LEVEL 2')}}
function level2(dt){t+=dt;if(foot.stun>0){foot.stun-=dt;return}if(foot.tele>0){foot.tele=Math.max(0,foot.tele-dt);if(foot.tele===0){foot.visible=true;foot.y=-180;foot.vy=720;foot.landed=false}return}if(!foot.visible){if(Math.random()<dt*.75)foot.tele=.8;return}foot.y+=foot.vy*dt;foot.vy+=1550*dt;if(foot.y>=-15&&!foot.landed){foot.y=-15;foot.vy=0;foot.landed=true;burst(foot.x+130,470,42,'#d9bd82');shell.classList.add('shake');setTimeout(()=>shell.classList.remove('shake'),280);if(hit(player,{x:foot.x+15,y:230,w:230,h:100}))damage(true);setTimeout(()=>{if(running&&foot.hp>0){foot.visible=false;foot.y=-220;foot.landed=false}},700)}}
function win(){const n=(+localStorage.getItem('onamOdysseyWins')||0)+1;localStorage.setItem('onamOdysseyWins',n);running=false;best=Math.max(best,score);localStorage.setItem('onamOdysseyBest',best);burst(480,250,120,'#ffe37a');show('ONAM VICTORY! 🌼','Maveli defeated Vamana’s challenge!<br><b>Score: '+score+' • Best: '+best+'</b><br>🌼 Pookalam progress: '+Math.min(3,n)+'/3 rings complete.','PLAY AGAIN')}
function palm(x,y,s=1){g.save();g.translate(x,y);g.strokeStyle='#376d3d';g.lineWidth=8*s;g.beginPath();g.moveTo(0,0);g.quadraticCurveTo(-8*s,-55*s,4*s,-120*s);g.stroke();g.fillStyle='#2f7b43';for(let a=0;a<6;a++){const ang=a*Math.PI/3-Math.PI/2;g.save();g.rotate(ang);g.beginPath();g.ellipse(0,-125*s,52*s,11*s,0,0,Math.PI*2);g.fill();g.restore()}g.restore()}
function laneX(l){return 150+l*330}
function bg(){const q=g.createLinearGradient(0,0,0,H);q.addColorStop(0,'#37acd3');q.addColorStop(.58,'#9ed8b1');q.addColorStop(1,'#e9d79e');g.fillStyle=q;g.fillRect(0,0,W,H);g.fillStyle='#fff0a0';g.beginPath();g.arc(790,70,45,0,Math.PI*2);g.fill();palm(70,310,.85);palm(870,300,.95);palm(260,285,.65);palm(700,290,.7)}
function drawRoad(){g.fillStyle='#9a6a43';g.beginPath();g.moveTo(270,540);g.lineTo(420,175);g.lineTo(540,175);g.lineTo(690,540);g.closePath();g.fill();g.fillStyle='#c18a54';g.beginPath();g.moveTo(320,540);g.lineTo(438,175);g.lineTo(522,175);g.lineTo(640,540);g.closePath();g.fill();for(let l=0;l<2;l++){g.strokeStyle='rgba(255,235,160,.8)';g.lineWidth=5;g.setLineDash([28,28]);g.beginPath();g.moveTo(420+l*120,540);g.lineTo(438+l*84,175);g.stroke()}g.setLineDash([]);for(let z=0;z<8;z++){const y=190+z*48,w=30+z*12;g.fillStyle='#805234';g.fillRect(480-w,y,w*2,5)}}
function drawTemple(){g.fillStyle='#8b5b35';g.fillRect(70,220,120,115);g.fillStyle='#c49343';g.beginPath();g.moveTo(55,220);g.lineTo(130,165);g.lineTo(205,220);g.closePath();g.fill();g.fillStyle='#7d3d2b';g.fillRect(92,265,30,70);g.fillRect(138,265,30,70);g.fillStyle='#e0b84c';g.fillRect(65,335,130,10);g.fillStyle='#70452f';g.fillRect(770,225,115,110);g.fillStyle='#bd8b3c';g.beginPath();g.moveTo(755,225);g.lineTo(827,172);g.lineTo(900,225);g.closePath();g.fill()}
function draw1(){drawRoad();drawTemple();for(const x of [80,330,580,830]){g.fillStyle='#d4af37';g.beginPath();g.arc(x,390,18,0,Math.PI*2);g.fill();g.fillStyle='#fff1a0';g.beginPath();g.arc(x,390,8,0,Math.PI*2);g.fill()}for(const u of umb){if(u.got||u.z<-40)continue;const d=Math.max(0,Math.min(1,(1050-u.z)/900)),y=155+d*255,s=.55+d*.55,x=laneX(u.lane);g.save();g.translate(x,y+Math.sin(u.bob)*5);g.scale(s,s);g.strokeStyle='#ffe36e';g.lineWidth=4;g.fillStyle='#d4af37';g.beginPath();g.arc(0,0,20,Math.PI,0);g.fill();g.stroke();g.beginPath();g.moveTo(0,0);g.lineTo(0,26);g.stroke();g.restore()}for(const h of hazards){if(h.z>1050||h.z<-80)continue;const d=Math.max(0,Math.min(1,(1050-h.z)/900)),y=155+d*255,x=laneX(h.lane),s=.5+d*.65;g.save();g.translate(x,y);g.scale(s,s);if(h.kind==='coconut'){g.rotate(h.rot);g.fillStyle='#704225';g.beginPath();g.arc(0,-18,23,0,Math.PI*2);g.fill();g.strokeStyle='#b27b45';g.lineWidth=4;g.stroke()}else if(h.kind==='barricade'){g.fillStyle='#7b3d27';g.fillRect(-42,-52,84,52);g.fillStyle='#e4b33c';g.fillRect(-42,-40,84,10);g.fillRect(-42,-15,84,10);g.fillStyle='#553a25';g.fillRect(-50,0,12,10);g.fillRect(38,0,12,10)}else{g.fillStyle='#d5b24a';g.fillRect(-52,-90,104,90);g.fillStyle='#a23b2e';g.fillRect(-48,-75,96,18);g.fillStyle='#f3d36b';g.fillRect(-48,-48,96,14)}g.restore()}}
function draw2(){g.fillStyle='#6f9054';g.fillRect(0,0,W,410);g.fillStyle='#d5b978';g.fillRect(0,410,W,130);for(let i=0;i<9;i++){let x=45+i*110;g.fillStyle='#73452f';g.fillRect(x,285,70,65);g.fillStyle='#a87a39';g.beginPath();g.moveTo(x-10,285);g.lineTo(x+35,250);g.lineTo(x+80,285);g.closePath();g.fill()}if(foot.tele>0){g.fillStyle='rgba(25,18,10,.38)';g.beginPath();g.ellipse(foot.x+130,455,155,38,0,0,Math.PI*2);g.fill();g.fillStyle='#fff0a0';g.font='900 18px system-ui';g.fillText('STOMP IN '+foot.tele.toFixed(1),foot.x+62,400)}if(foot.visible){g.save();g.translate(foot.x,foot.y);g.fillStyle='#b86c40';g.beginPath();g.ellipse(130,125,120,180,0,0,Math.PI*2);g.fill();g.beginPath();g.ellipse(130,270,115,72,0,0,Math.PI*2);g.fill();for(let i=0;i<5;i++){g.beginPath();g.ellipse(45+i*43,305,29,34,0,0,Math.PI*2);g.fill()}g.strokeStyle='#e9bf3e';g.lineWidth=12;g.beginPath();g.arc(130,250,108,.1,3.05);g.stroke();g.fillStyle='#fff1a0';g.font='900 18px system-ui';g.fillText('HP '+foot.hp,105,55);g.restore()}}
function drawPlayer(){g.save();g.translate(player.x+19,player.y+32);if(inv>0&&Math.floor(inv*12)%2===0)g.globalAlpha=.45;const squash=player.ground?1:1+.08*Math.sin(player.jumpT*14);g.scale(1/squash,squash);g.fillStyle='#f4ead2';g.fillRect(-11,8,9,30);g.fillRect(3,8,9,30);g.fillStyle='#ead9ae';g.fillRect(-16,-3,32,17);g.fillStyle='#236c42';g.fillRect(-16,-4,32,6);g.fillStyle='#7c4529';g.beginPath();g.arc(0,-14,17,0,Math.PI*2);g.fill();g.fillStyle='#b36a3b';g.beginPath();g.arc(0,-22,12,0,Math.PI*2);g.fill();g.fillStyle='#d4a52f';g.beginPath();g.moveTo(-12,-31);g.lineTo(12,-31);g.lineTo(7,-41);g.lineTo(0,-33);g.lineTo(-7,-41);g.closePath();g.fill();g.strokeStyle='#5a3a1b';g.lineWidth=3;g.beginPath();g.moveTo(9,5);g.lineTo(attackTimer?73:43,-27);g.stroke();if(defending){g.strokeStyle='#8eeaff';g.lineWidth=5;g.globalAlpha=.75;g.beginPath();g.arc(0,0,50,0,Math.PI*2);g.stroke()}g.restore()}
function render(){bg();level===1?draw1():draw2();drawPlayer();for(const d of dodgeMarks){g.globalAlpha=d.life;g.fillStyle='#fff1a1';g.font='900 18px system-ui';g.fillText('+5 Points',d.x,d.y)}for(const q of particles){g.globalAlpha=Math.max(0,q.life);if(q.size){g.font='900 '+q.size+'px system-ui';g.fillStyle=q.c;g.fillText(q.text||'',q.x,q.y)}else{g.fillStyle=q.c;g.fillRect(q.x,q.y,4,4)}}g.globalAlpha=1}
function tick(now){if(!running||paused){render();return}const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;try{move(dt);level===1?level1(dt):level2(dt);particlesTick(dt);render();raf=requestAnimationFrame(tick)}catch(e){console.error(e);running=false;show('GAME ERROR','The game stopped safely.<br><small>'+String(e?.message||e)+'</small>','RESTART')}}
start.onclick=()=>{if(title.textContent==='LEVEL 2 • VAMANA’S CHALLENGE'){running=true;paused=false;hide();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(tick);return}if(title.textContent==='ONAM VICTORY! 🌼'||title.textContent==='TRY AGAIN'||title.textContent==='GAME ERROR')fresh();running=true;paused=false;hide();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(tick)};
pause.onclick=()=>{if(!running)return;paused=!paused;pause.textContent=paused?'▶':'Ⅱ';if(paused)show('GAME PAUSED','Take a breath, then continue Maveli’s Onam adventure.','RESUME');else{hide();last=performance.now();raf=requestAnimationFrame(tick)}};
restartBtn.onclick=()=>{fresh();running=true;hide();last=performance.now();raf=requestAnimationFrame(tick)};
document.querySelectorAll('[data-control]').forEach(b=>{const k=b.dataset.control;b.addEventListener('pointerdown',e=>{e.preventDefault();if(k==='jump')jump();else if(k==='attack')attack();else if(k==='defend')defend();else if(k==='left')changeLane(-1);else if(k==='right')changeLane(1)});b.addEventListener('pointerup',e=>e.preventDefault())});
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft'||e.code==='KeyA')changeLane(-1);if(e.code==='ArrowRight'||e.code==='KeyD')changeLane(1);if(e.code==='Space'||e.code==='ArrowUp'||e.code==='KeyW')jump();if(e.code==='KeyF')attack();if(e.code==='ShiftLeft'||e.code==='ShiftRight')defend();if(e.code==='KeyP')pause.click()});
window.addEventListener('blur',()=>{keys.left=keys.right=false});
setup1();hud();render();